// facet -> reputation dictionary-item address on the Tribunal contract.
// Generated by scripts/build-rep-map.mjs from each judge's register_judge tx.
// The slots are stable, so this is committed and imported directly (no fs, so it
// works the same under tsx and the Next bundler).
export const JUDGE_REP_MAP: Record<string, string> = {
  authenticity: "4625df520d29030484cbdffe1ef0a5c33f4dff8028d04289c61f7afc3c389245",
  solvency: "0b58f6268cec4b1da08e6e78e24fcc0689bcdb2da3ae36e74e846664ae0e6ca3",
  custodian: "2cf2cf07b0d383cf7361328c21a117ba9c4b59eada0b4721be30d58f6b84ecd2",
  valuation: "57e86dce084bde49cdc566178f75c544d21c5152fb5711fbda666a5cfd2a9127",
};
