// facet -> reputation dictionary-item address on the Tribunal contract.
// Generated by scripts/build-rep-map.mjs from each judge's register_judge tx.
// The slots are stable, so this is committed and imported directly (no fs, so it
// works the same under tsx and the Next bundler).
export const JUDGE_REP_MAP: Record<string, string> = {
  authenticity: "ef2c6eb7fd0891538bbb6338e38e3d9efcdd9ae914dac65bde50734f5f27c580",
  solvency: "92fb5ca4c41f4b0b3b821b6e83b16246a3f7aa23b16330a62202cec511679f60",
  custodian: "2cabee0a295c35a013d73f3b5542ca759fc3644da1ce6ee58df5172a5f68740e",
  valuation: "66df778618dc4bddcf59c036d9aba9b12d75d29773fb6d9461f7315e967f37bc",
};
